### ISSUE TITLE
FN: encrypt-data-using-camellia - 112f9f0e8d349858a80dd8c14190e620

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa-rules#105]
## Summary

`encrypt-data-using-camellia` doesn't match on 112f9f0e8d349858a80dd8c14190e620

## Examples

112f9f0e8d349858a80dd8c14190e620

Reference:
 - https://krabsonsecurity.com/2020/08/22/bitrat-the-latest-in-copy-pasted-malware-by-incompetent-developers/

From a quick glance at the binary, the s-box from https://github.com/calccrypto/Encryptions/blob/master/Encryptions/Camellia_Const.h#L35 can be found at address 0x008cb760 (offset 0x004ca160)

## Possible improvements

I'm not familiar with Camellia or `encrypt-data-using-camellia` enough to understand specifically what the existing logic is looking for, but hopefully it's as simple as adding the s-box bytes (and maybe some of the sigma byte sequences as well) from above into the rule.

**Comment by williballenthin** [comment]
sbox reference in in function 0x4CE384

![image](https://user-images.githubusercontent.com/156560/91491238-fdc8d500-e870-11ea-943e-8ad4306fd330.png)
![image](https://user-images.githubusercontent.com/156560/91491260-05887980-e871-11ea-9e39-b6876948ec1b.png)

the camellia constants in the reference look like this (bring inline just for ease of access):
![image](https://user-images.githubusercontent.com/156560/91491513-657f2000-e871-11ea-9682-df1f93e757d3.png)

capa rule currently looks like this:

![image](https://user-images.githubusercontent.com/156560/91491543-7039b500-e871-11ea-9be9-d784263dd88f.png)

this first line of the capa logic (sp1110) looks similar to the s-box, though it seems to repeat bytes with interspersed data. I've double checked the referenced sample and indeed it does use this unusual format.
![image](https://user-images.githubusercontent.com/156560/91491740-bb53c800-e871-11ea-80fe-70b9e846c3ca.png)

i think we can add a new `bytes: ...` term under the top level `or` that references the first 256 bytes of the s-box byte array. just like @recvfrom suggested. would you like to propose the updates the rule in a PR? if you do, please also add yourself into the `authors` list in the rule meta.

something like:

```yaml
bytes: 0x70, 0x82, ... 0x80, 0x9e = Camellia_SBox
```

**Comment by recvfrom** [comment]
Thanks for doing the heavy-lifting to investigate this!

I'll update the rule and submit a PR. I'll also look into whether an update could be made to the section that looks for the sigmas
