### ISSUE TITLE
host-interaction/network/dns/resolve

### ISSUE THREAD

**Issue by toomanybananas** [fireeye/capa-rules#115]
## Summary

host-interaction/network/dns/resolve is overly broad, firing on any function that uses inet_addr (https://github.com/fireeye/capa-rules/blob/master/host-interaction/network/dns/resolve/resolve-dns.yml#L12). This function really has nothing to do with DNS (it merely converts an IP address string into the internal 32 bit int representation).

## Examples

For an example, see sample 3467147283c76dd00e2f6c34e1118ada3577405dd11229c7ae1ebd4e6a37fef2 function at 0x405E60

## Possible improvements

Likely just remove inet_addr from the list. I don't think it adds anything over the other function matches.

**Comment by williballenthin** [comment]
good point, thanks for reporting!
