### ISSUE TITLE
reference anti-VM strings targeting Xen

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#127]
## Summary

`regex(/Xen/i)` matches falsely on strings, for example `szExeName`

## Possible improvements

Match case-sensitive or add `^`/`$` marker(s)

**Comment by johnk3r** [comment]
Hello @mr-tz.

I can work on that rule. Do you have a sample?

**Comment by mr-tz** [comment]
Oh, thanks, this was actually fixed in #192 already.
