### ISSUE TITLE
s/credit card/payment card/g

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#178]
thanks to @reginaelwell  for pointing out that we should use the term "payment card" versus "credit card" since things like debit cards do pass the luhn algorithm

**Comment by re-fox** [comment]
Good point.  If this issue isn't resolved soon I'll make the changes.

**Comment by re-fox** [comment]
Changes addressed in #182.  I'll close out the issue.  Let me know if it needs to be re-opened.
