### ISSUE TITLE
FP:  anti-vm, cpuid used in library function

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa-rules#18]
@Ana06
> `cpuid` is used in the `__get_sse2_info` library function:
> 
> ![image](https://user-images.githubusercontent.com/16052290/85728093-e138e100-b6f7-11ea-84a3-0ba1f59ce0e1.png)
> 
> This happens in the C++ lab. I think it is not uploaded here. Not sure if I should/can add it to the project.

@mr-tz
> Good find.
> You could upload it to the `tests/data/` directory. We use git-lfs for these files (see `.gitattributes`)

**Comment by mr-tz** [comment]
handled in https://github.com/fireeye/capa-rules/pull/208
related to https://github.com/fireeye/capa/issues/74
