### ISSUE TITLE
Additional shlwapi API's for get/set/open/create registry key operations 

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa-rules#199]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

The rules under `host-interaction/registry` could benefit from adding the APIs from shlwapi for registry operations.

A large list of them can be found here-> https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions

One of the rules `host-interaction/registry/delete/` already has `SHDeleteKey` and `SHDeleteValue` in it.  So this one could most likely remain as-is.

Some quick examples would be:

For Open Key:
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shregopenuskeya

For Query Key:
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shqueryvalueexa

Get/Set Value:
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shsetvaluea
https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-shreggetvaluea

## Features
```
SHCopyKey
SHDeleteEmptyKey
SHEnumKeyEx
SHEnumValue
SHGetValue
SHQueryInfoKey
SHQueryValueEx
SHRegCloseUSKey
SHRegCreateUSKey
SHRegDeleteEmptyUSKey
SHRegDeleteUSValue
SHRegDuplicateHKey
SHRegEnumUSKey
SHRegEnumUSValue
SHRegGetBoolUSValue
SHRegGetIntW
SHRegGetPath
SHRegGetUSValue
SHRegOpenUSKey
SHRegQueryInfoUSKey
SHRegQueryUSValue
SHRegSetPath
SHRegSetUSValue
SHRegWriteUSValue
SHSetValue
```

### Namespace
`host-interaction/registry`

### References
https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions
https://docs.microsoft.com/en-us/windows/win32/shell/shlwapi-reg
https://www.geoffchappell.com/studies/windows/shell/shlwapi/api/index.htm

**Comment by mike-hunhoff** [comment]
@re-fox with #210 I added all of these except the following:

- `SHCopyKey`
- `SHRegCloseUSKey`
- `SHRegDuplicateHKey`

**Comment by re-fox** [comment]
Thanks @mike-hunhoff!  The PR #210 had a lot of great additions (and you saved me a bit of work).

I'll go ahead and close the issue since all relevant functions have been added.
