### ISSUE TITLE
Merge FNV hashing rules

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#203]
There's already a rule in the nursery: https://github.com/fireeye/capa-rules/blob/master/nursery/hash-data-using-fnv.yml

These should be merged.

_Originally posted by @mr-tz in https://github.com/fireeye/capa-rules/issues/201#issuecomment-747323500_

**Comment by re-fox** [comment]
I missed that.  I was searching for the constants.  I'll make the merge and submit a PR.

**Comment by mr-tz** [comment]
Closed via #204
