### ISSUE TITLE
detect BCrypt use

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#21]
The following:
- [x] BCryptDecrypt
- [x] BCryptEncrypt
- [x] BCryptHash
- [x] BCryptHashData
- [x] BCryptGenerateSymmetricKey
- [x] BCryptGenerateKeyPair
- [x] BCryptGenRandom

**Comment by johnk3r** [comment]
Hello @mike-hunhoff 

I will work on that rule.

**Comment by mike-hunhoff** [comment]
Hi @johnk3r! The only API we have left to cover from this list is `BCryptGenRandom`. Unfortunately I have not found a public sample that uses this particular API, but for the time being you can create the rule and place it in the [rule nursery](https://github.com/fireeye/capa-rules#rule-nursery). Once a public sample is found (or if you already have one in mind) we can then graduate the rule.

I'll assign this task to you, thank you!

**Comment by johnk3r** [comment]
@mike-hunhoff

**Comment by johnk3r** [comment]
- [ ] BCryptGenRandom

**Comment by mike-hunhoff** [comment]
Wonderful @johnk3r!

Let's create a new rule under `data-manipulation/prng` for the generation of random numbers using `BCryptGenRandom`.

**Comment by mr-tz** [comment]
> Let's create a new rule under `data-manipulation/prng` for the generation of random numbers using `BCryptGenRandom`.

Let's add a new rule since the random number isn't necessarily tied to encryption.

**Comment by johnk3r** [comment]
> 
> 
> > Let's create a new rule under `data-manipulation/prng` for the generation of random numbers using `BCryptGenRandom`.
> 
> Let's add a new rule since the random number isn't necessarily tied to encryption.
> 
> Edit: we could also add other similar functions to this new rule, e.g. https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptgenrandom

Ok man.

**Comment by johnk3r** [comment]
Hi,

I need help to define the rule name...
