### ISSUE TITLE
offline registry manipulation with offreg.dll

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#211]
originally suggested here: https://twitter.com/0gtweet/status/1344363283063701504?s=20

documentation:
- https://docs.microsoft.com/en-us/windows/win32/devnotes/offline-registry-library-portal
- https://docs.microsoft.com/en-us/windows/win32/devnotes/offline-registry-library-functions

**Comment by johnk3r** [comment]
I will work on it
