### ISSUE TITLE
[Rule Idea] - VEST Encryption Algorithm

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa-rules#231]
## Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary
Torisma malware uses VEST for encryption, highlighted in the following snippet from https://blogs.jpcert.or.jp/en/2021/01/Lazarus_malware2.html#2.  

> As a response to this request, an encrypted and Base64-encoded module ("+" is replaced by a space ) is downloaded. Torisma uses VEST-32 algorithm [2] for encryption. In the samples confirmed by JPCERT/CC, the encryption key was identical, which was "ff7172d9c888b7a88a7d77372112d772" (as in Figure 2). This encryption algorithm is also used for encrypting C2 server information in the configuration.

## Examples
```
f77a9875dbf1a1807082117d69bdbdd14eaa112996962f613de4204db34faba7
```

## Features
Vest s-box can be observed at `180017280` in the above sample.

## Additional context
VEST C implementation can be found at http://www.ecrypt.eu.org/stream/p2ciphers/vest/vest_p2source.zip

### Namespace
`
data-manipulation/encryption/vest/
`

### References
- https://blogs.jpcert.or.jp/en/2021/01/Lazarus_malware2.html
- https://www.ecrypt.eu.org/stream/vest.html

**Comment by williballenthin** [comment]
closed in #244
