### ISSUE TITLE
resolve DNS: doesn't match on referenced example: Fix the rule logic or provide a different example

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#239]
from `lint.py --thorough`

**Comment by johnk3r** [comment]
Please let me try to help you in this case.

**Comment by johnk3r** [comment]
Hello,

can they close this issue?

**Comment by mr-tz** [comment]
Yes, thank you! If you use "fixes" or "closes", e.g. `closes #239` in your PR description this can happen automatically on merging.
