### ISSUE TITLE
delete registry key: doesn't match on referenced example: Fix the rule logic or provide a different example

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#241]
from `lint.py --thorough`

**Comment by johnk3r** [comment]
Please let me try to help you in this case.

**Comment by williballenthin** [comment]
awesome @johnk3r! can you review the rule and compare with the listed sample to see if there's a obvious mistake in the rule logic?

**Comment by johnk3r** [comment]
Yes man.

I removed the conflicting sample and added a new one. There was no need to change the rule logic.

**Comment by johnk3r** [comment]
Excludes PR ...

I don't know why but my latest PRs are always giving the same error:

`"Error: the head commit for this pull_request event is not ahead of the base commit. Submit a problem in the GitHub repository for this action." `

**Comment by mr-tz** [comment]
That's an issue with the GitHub action we use to get the modified files. Rebasing may help in these cases or are you using the web UI?

**Comment by johnk3r** [comment]
Thank you. I'll try rebasing next time ...

**Comment by johnk3r** [comment]
Hello,

can they close this issue?

**Comment by mike-hunhoff** [comment]
awesome, thank you @johnk3r! closed by #257
