### ISSUE TITLE
rule idea: detect Nim binaries

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#246]
https://nim-lang.org/

**Comment by mike-hunhoff** [comment]
we may also want to add this rule here:

https://github.com/fireeye/capa/blob/ef41d74b8233668932eaa652202b0bcb0fd7b5af/capa/main.py#L159

**Comment by williballenthin** [comment]
https://github.com/byt3bl33d3r/OffensiveNim

**Comment by mr-tz** [comment]
@MalwareMechanic 😉
