### ISSUE TITLE
simulate CTRL ALT DEL: doesn't match on referenced example: Fix the rule logic or provide a different example

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#249]
from `lint.py --thorough`

**Comment by johnk3r** [comment]
Please let me try to help you in this case.

**Comment by williballenthin** [comment]
awesome @johnk3r! can you review the rule and compare with the listed sample to see if there's a obvious mistake in the rule logic?

**Comment by johnk3r** [comment]
Hello,

can they close this issue?

**Comment by mike-hunhoff** [comment]
awesome, thank you @johnk3r. closed by #257
