### ISSUE TITLE
check for unmoving mouse cursor: doesn't match on referenced example: Fix the rule logic or provide a different example

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#251]
from `lint.py --thorough`

**Comment by williballenthin** [comment]
@BitsOfBinary

**Comment by mr-tz** [comment]
appears to be wrong file, may need new example or move to nursery

**Comment by johnk3r** [comment]
Please let me try to help you in this case.

**Comment by williballenthin** [comment]
awesome @johnk3r! can you review the rule and compare with the listed sample to see if there's a obvious mistake in the rule logic?

**Comment by BitsOfBinary** [comment]
Sorry folks, I had been referencing the packed version of the example binary in the rule! I've uploaded an unpacked version of the Gozi binary with that technique, and corrected the example hash in the rule, so hopefully that should resolve the false negative.

**Comment by BitsOfBinary** [comment]
Also by uploaded I mean I uploaded the sample to VT for reference. If someone could add that to the capa-testfiles repo I would appreciate it :) 

Sample:
https://www.virustotal.com/gui/file/d7ff81ff775d4ab50d31ac1e962c8c4dea7ff9f280aa2b42ddd06760a5665002/detection

**Comment by johnk3r** [comment]
Hello @BitsOfBinary ,

upload done. Can you adjust the function of the rule for **0x4010ED**?
