### ISSUE TITLE
EXE4J

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#261]
https://www.ej-technologies.com/download/exe4j/files
filemd5=0a29569004ceb84e86e3a551b485dc1c

**Comment by williballenthin** [comment]
```
%se4j_p%d.tmp
com/install4j/runtime/launcher/WinLauncher
com/exe4j/runtime/WinLauncher
c:\i4j_nlog
EXE4J_LOG
```

**Comment by johnk3r** [comment]
Hi.

I will work on it.

**Comment by johnk3r** [comment]
You can help me with:

Rule name:
TTP:
MBC:

? 
![exej](https://user-images.githubusercontent.com/6247648/108288494-713a0800-716b-11eb-992b-9ed5955a9fde.png)

**Comment by mr-tz** [comment]
> exe4j is a Java exe maker that helps you integrate your Java applications into the Windows operating environment. exe4j helps you with splash screens, JRE detection, error handling and much more. 

- name: compiled with exe4j
- namespace: compiler/exe4j

or alternatively packaged via exe4j (executable/installer/exe4j)?

- references: https://www.ej-technologies.com/download/exe4j/files

**Comment by johnk3r** [comment]
Thanks
