### ISSUE TITLE
linter/documentation: export overlap in ntdll.dll and ntoskrnl.exe

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#267]
There are ~625 exports that overlap between `ntdll.dll` and `ntoskrnl.exe`. To improve our coverage of both user and kernel space binaries we should not specify a module for these overlapped exports.

e.g. `ZwAllocateVirtualMemory` should be used instead of `ntdll.ZwAllocateVirtualMemory`.

suggestions:

@mr-tz 
> Great! I think documenting this would be a very good idea. Either at https://github.com/fireeye/capa-rules/blob/master/doc/format.md#api or even better as a linter suggestion?

It would be really cool to see this as a linter suggestion, preferably one that identifies an overlapping export and notifies the user. However, this would require maintaining a list of overlap.

Alternatively the linter could inform a user that they should check if the specified export is found in both `ntdll.dll` and `ntoskrnl.exe` and, if true, suggest removing the specified module.

**Comment by mr-tz** [comment]
I think a lint for API features containing `ntdll` or `ntoskrnl` and a warning suffices.

**Comment by mike-hunhoff** [comment]
closed by https://github.com/fireeye/capa/pull/428
