### ISSUE TITLE
rule idea: check OS version new/update

### ISSUE THREAD

**Issue by mike-hunhoff** [fireeye/capa-rules#28]
Add new rule or update existing to detect OS version checks via following `kernel32` APIs:

- `VerSetConditionMask`
- `VerifyVersionInfo`

**Comment by johnk3r** [comment]
Hello @mike-hunhoff .

I will work on that rule.

**Comment by johnk3r** [comment]
sample: 8ed9a60127aee45336102bf12059a850

**Comment by mike-hunhoff** [comment]
Hi @johnk3r! Thank you for finding a sample. I will assign this task to you, thank you!

**Comment by johnk3r** [comment]
- [ ]     VerSetConditionMask
- [ ]     VerifyVersionInfo

**Comment by johnk3r** [comment]
@mike-hunhoff ,

Would it be interesting to leave in the same rule?

I ask why the API GetVersion (Ex) was deprecated, too, we will need to make adjustments to the rule that is in production.

https://github.com/fireeye/capa-rules/blob/master/host-interaction/os/version/get-os-version.yml

**Comment by mike-hunhoff** [comment]
@johnk3r looking back at the existing rule [get-os-version.yml](https://github.com/fireeye/capa-rules/blob/master/host-interaction/os/version/get-os-version.yml) I feel it should instead be named `check-os-version.yml` to better fit the intention. With this change the rule you added in fdf3afe could be combined with the existing rule.

Does it sound reasonable to rename the existing rule [get-os-version.yml](https://github.com/fireeye/capa-rules/blob/master/host-interaction/os/version/get-os-version.yml) to `check-os-version.yml` and combine it with your rule committed in fdf3afe? I feel this is a better fit all around and improves the existing rule.

**Comment by johnk3r** [comment]
Hello @mike-hunhoff ,

I have an open PR. Once it's completed, I'll update this rule. 

Grateful

**Comment by johnk3r** [comment]
Hi,

I will work on that rule again.
