### ISSUE TITLE
check if process is running under wine

### ISSUE THREAD

**Issue by mr-tz** [fireeye/capa-rules#282]
## Summary

`regex(/Wine/i)` matches on `NotifyWinEvent`

Need to improve regex.

**Comment by re-fox** [comment]
That's my rule, I'll check it out.

**Comment by re-fox** [comment]
@mr-tz I updated the rule (merged) and removed the offending regex. 

I looked back through other samples in `capa-testfiles` and IIRC the regex was inserted for an opportunistic match.  Fortunately, removing the string doesn't introduce false negatives.  

Thanks for posting the FP.  Happy to fix it.
