### ISSUE TITLE
capture-webcam-image

### ISSUE THREAD

**Issue by recvfrom** [fireeye/capa-rules#285]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary

Let's have a rule that detects a system's webcam being used to capture a picture

## Examples

Ex: Calling `capCreateCaptureWindow` + calling `SendMessage` with `WM_CAP_DRIVER_CONNECT` + calling `SendMessage` with `WM_CAP_FILE_SAVEDIB` (and maybe optionally calling `capGetDriverDescription`)
 - Source for an implementation in meterpreter: https://github.com/rapid7/meterpreter/blob/d338f702ce8cb7f4e550f005ececaf5f3cadd2bc/source/extensions/espia/video.c#L19-L34
 - I think this might be an example of malware using this technique (it imports `capCreateCaptureWindowA` and `capGetDriverDescriptionA`) but haven't confirmed: https://www.virustotal.com/gui/file/a5deb825c9aa91d5f79a04dfa59d23340b34df3e598da1fbc6b7c2b39c9c074d/details
 - This technique is also highlighted in https://blog.talosintelligence.com/2021/02/obliquerat-new-campaign.html, but I'll need to ask which sample corresponds to the screenshot

## Features

See above

## Additional context

N/A

### Namespace
collection/webcam

### References

- https://docs.microsoft.com/en-us/windows/win32/multimedia/video-capture

### Other rule meta information

N/A

**Comment by johnk3r** [comment]
Please let me help you with that.
