### ISSUE TITLE
`capa` rule > `mbc` does not exactly conform to https://github.com/MBCProject/mbc-markdown!

### ISSUE THREAD

**Issue by evandrix** [fireeye/capa-rules#316]
i had to spend time to go through the output, to clean up the following mismatches/inconsistencies 😡

- ~~`Anti-Behavioral Analysis::Detect Debugger`~~ => `Anti-Behavioral Analysis::Debugger Detection`
- `Anti-Behavioral Analysis::Virtual Machine Detection::Unique Hardware/Firmware Check`
  - 2 cases i found for this, depending on rule name
  - if rule name == "reference the VMWare IO port", then mbc = "Anti-Behavioral Analysis::Virtual Machine Detection::Unique Hardware/Firmware Check - I/O Communication Port [B0009.025]"
  - if rule name == "reference processor manufacturer constants", then mbc = "Anti-Behavioral Analysis::Virtual Machine Detection::Instruction Testing - CPUID [B0009.034]" (! it's not even the same subcategory !)
- ~~`Anti-Static Analysis::Software Packing::Confuser [F0001.012]`~~ => `Anti-Static Analysis::Software Packing::Confuser [F0001.009]`
- ~~`Data::Encoding::Base64 [C0026.001]`~~ => `Data::Encode Data::Base64 [C0026.001]`
  - ~~`Data::Encoding::XOR [C0026.002]`~~ => `Data::Encode Data::XOR [C0026.002]`
  - similarly, ~~`...Decoding...`~~ => `...Decode Data...`
- ~~`Discovery::Analysis Tool Discovery::Process Detection [B0013.001]`~~ => `Discovery::Analysis Tool Discovery::Process detection [B0013.001]`
- ~~`File System::Write File [C0052]`~~ => `File System::Writes File [C0052]`
- ~~`Impact::Modify Hardware::CDROM [C0042.001]`~~ => `Impact::Modify Hardware::CDROM [B0042.001]`

additionally, is it too much to ask for/is there a reason for writing the a single-element: a string wrapped in an array/a list in the output, instead of structuring it, like the rest of the JSON output e.g. `{"ID":"B0001.008","tactic":"Anti-Behavioral Analysis","technique":"Debugger Detection","subtechnique":"IsDebuggerPresent"}`, following https://raw.githubusercontent.com/MBCProject/mbc-markdown/master/yfaq/mbc_matrix_with_ids.svg

**Comment by williballenthin** [comment]
thanks for reporting these inconsistencies @evandrix! do you want to take a stab at a PR or shall i assign myself?

**Comment by williballenthin** [comment]
> is there a reason for writing the [technique as] a single-element

in the rule yaml we use the single string because we believe it is most easy for a human to read while still being concise (i understand this might be debatable, but it is simply how we do things). parsing the string for the json output is a good idea - it reduces the number of times that programmatic users of capa have to write one-off parsers for the MBC information.

**Comment by williballenthin** [comment]
> Discovery::Analysis Tool Discovery::Process detection [B0013.001]

this looks like a typo in MBC

**Comment by williballenthin** [comment]
> similarly, ...Decoding... => ...Decode Data...

i didn't see any of these:
![image](https://user-images.githubusercontent.com/156560/114579662-5059d480-9c3b-11eb-93a8-4e967d16714c.png)
