### ISSUE TITLE
query Windows registry via WinAPI

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa-rules#320]
## Rule name

`query Windows registry via WinAPI`

## Summary

Query the Windows registry keys or values using the Windows API (WinAPI): https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions

## Examples

Publicly available samples that contain the capability this rule should detect:
- 36617f75817911327b379b557ec4f807
- fb20e67bf9b584df8994a8fefc563b4d

## References

Links or references to additional information on the capability (can also be included in the rule):

- https://attack.mitre.org/techniques/T1012
- https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions

## Namespace

Proposed namespace: `host-interaction/registry`. More details in https://github.com/fireeye/capa-rules/blob/master/doc/format.md#rule-namespace

## att&ck

`aka.mitre.att&ck.t1012`

**Comment by mr-tz** [comment]
is this different to `query or enumerate registry value`?

**Comment by Ana06** [comment]
🙈
