### ISSUE TITLE
create or modify Windows registry via WinAPI

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa-rules#321]
## Rule name

`create or modify Windows registry via WinAPI`

## Summary

Create Windows registry keys or values using the Windows API (WinAPI): https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions

## Examples

Publicly available samples that contain the capability this rule should detect:
- [PMA 03-02](https://github.com/fireeye/capa-testfiles/blob/master/Practical%20Malware%20Analysis%20Lab%2003-02.dll_)

## References

Links or references to additional information on the capability (can also be included in the rule):

- Practical Malware Analysis
- https://docs.microsoft.com/en-us/windows/win32/sysinfo/registry-functions

## Namespace

Proposed namespace: `host-interaction/registry`. More details in https://github.com/fireeye/capa-rules/blob/master/doc/format.md#rule-namespace

## att&ck

`aka.mitre.att&ck.t1012`

**Comment by mr-tz** [comment]
see `create or open registry key`, `set registry value`, `delete registry value`?

**Comment by Ana06** [comment]
🙈
