### ISSUE TITLE
[RULE NAME] Detect commands

### ISSUE THREAD

**Issue by 0xdarkfloyd** [fireeye/capa-rules#331]
Hello,

I have tried to detect commands of an oilrig backdoor sample but it failed, I have attached a screenshot and could you please advise whether I got it wrong. Thank you so much.
![capa_1](https://user-images.githubusercontent.com/22325879/115527095-51d26f00-a2c3-11eb-97c9-fb5ad2a7cb57.png)
:
rule:
  meta:
    name: commands
    namespace: communication
    author: darkfloyd@vxrl.hk
    scope: file
    mbc:
      - Communication::HTTP Communication::Commands [C0002.014]
    examples:
      - 6A352C3E55E8AE5ED39DC1BE7FB964B1:0x10002A30
  features:
    - and:
      - string: "cmd"
      - string: "upload"
      - string: "download"
      - string: "powershell.exe"

**Comment by 0xdarkfloyd** [comment]
Simply put as "or" instead of "and"

**Comment by mr-tz** [comment]
Note that some strings end with a `$`.
Looking for either of these strings using `or` will result in a lot of hits, so make sure that matches your goal.
