### ISSUE TITLE
Handful of new rules

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa-rules#336]
I recently worked my way through an old stealer/grabber (`5a2f620f29ca2f44fc22df67b674198f`) with the intent to build out capa-rules.

While doing this exercise, I found that many of the rules are subjectively "low quality" relying on pairings of strings.  

I wanted to share these rules, in case they may be useful.  I didn't roll these up into a giant PR until they received some peer review or qualitative analysis.  Capa's scope (in this case, all `function` level) results in the rules not being too prone to FP's, 

Let me know if these rules would be a welcome addition to the capa-rules main repository, and if not, I'll keep a fork with supplemental rules.   If a PR is decided, the rules have been linted with `--thorough` and `capafmt` has been applied.

https://github.com/re-fox/capa-rules/tree/master/collection/file-managers

**Comment by williballenthin** [comment]
Wow, this is a great collection!

I understand your concern about these being pairings of strings, though thanks to the scope and length of the strings, suspect they'd still be useful. It also seems like these might be fairly rarely seen - but I'm not convinced that means we should not write rules for interesting capabilities.

Therefore, I'd vote for opening a PR and merging these.

**Comment by re-fox** [comment]
Thanks for the help and input!  Closing the issue.
