### ISSUE TITLE
Install Digital Certificate

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#355]
https://attack.mitre.org/techniques/T1608/003

**Comment by williballenthin** [comment]
https://www.fireeye.com/blog/threat-research/2012/08/hikit-rootkit-advanced-persistent-attack-techniques-part-2.html

**Comment by williballenthin** [comment]
`certmgr.exe`

**Comment by mr-tz** [comment]
I think this technique is focused on the attacker infrastructure vs. infected hosts.

> Installation of digital certificates may take place for a number of server types, including web servers and email servers. 

Willi's reference and features are a good fit for https://attack.mitre.org/techniques/T1553/004/

**Comment by mr-tz** [comment]
Closing this and tracking now in #373.
