### ISSUE TITLE
capa2yara

### ISSUE THREAD

**Issue by ruppde** [fireeye/capa-rules#384]
I've converted 403 capa rules to yara:
https://github.com/ruppde/yara_rules/tree/main/capa2yara

Do you want them in this repository? And the script to capa/scripts?

**Comment by mr-tz** [comment]
Wow, very cool! If you can send a PR for the script in `capa/scripts` that'd be awesome.

I'm not sure if/where we want to store the Yara rules or if can let users do that as needed.

**Comment by ruppde** [comment]
sure, the code just needs some clean up

**Comment by ruppde** [comment]
see https://github.com/fireeye/capa/pull/561

**Comment by ruppde** [comment]
btw, here's is a loose collection of things that bumped my while converting the rules to yara. none of them is really bad but they could be improved:

* lots of regexes contain .* which yara complains about because it slows down the search. had to convert them to {,1000}
* capa accepts "string: /com/exe4j/runtime/exe4jcontroller/i" without escaping the inner slashes
* there were several regexes like e.g. string: /A09E667F3BCC908B/i which could be perfectly done with string search but there's no way to ignore casing on strings.

**Comment by williballenthin** [comment]
do you have a blog post or similar in preparation that we can link to? this is a really neat effort and i believe others would like to hear about it.

**Comment by ruppde** [comment]
thanks, there's just https://github.com/ruppde/yara_rules/tree/main/capa2yara

**Comment by williballenthin** [comment]
added in https://github.com/fireeye/capa/pull/561
