### ISSUE TITLE
check-http-status-code is a little loose

### ISSUE THREAD

**Issue by williballenthin** [fireeye/capa-rules#418]
as noted in https://github.com/fireeye/capa/issues/641, communication/http/client/check-http-status-code is a bit loose. it will match with all of the following:

  - `cmp`
  - `0x13`
  - `0x200`

these numbers aren't very large, so they might reasonably seen in structure manipulation code, etc. we should consider tightening up this rule, at least with this combination of features.

**Comment by mr-tz** [comment]
The function graph this matches on in the provided sample (`gobble_file` in `ls`)...

![2021-09-09_17-54-58](https://user-images.githubusercontent.com/17606537/132720211-973fd003-54e0-402f-b236-2ed0c1bda0c1.png)

Given the function size and complexity FPs are unfortunately likely and I couldn't identify a really convincing way to tighten the rule here.

**Comment by mr-tz** [comment]
Adding a `os` marker at least resolves the Linux `ls` FP.
