### ISSUE TITLE
Non-compliant MITRE ATT&CK Rule

### ISSUE THREAD

**Issue by evandrix** [fireeye/capa-rules#428]
- https://github.com/fireeye/capa-rules/blob/93ea28dd325c2db5e080272063c4dc12276c49cd/host-interaction/uac/bypass/bypass-uac-via-token-manipulation.yml#L8
- https://github.com/fireeye/capa-rules/blob/93ea28dd325c2db5e080272063c4dc12276c49cd/host-interaction/uac/bypass/bypass-uac-via-appinfo-alpc.yml#L8
- https://github.com/fireeye/capa-rules/blob/93ea28dd325c2db5e080272063c4dc12276c49cd/nursery/bypass-uac-via-scheduled-task-environment-variable.yml#L8 
- https://github.com/fireeye/capa-rules/blob/b6485d2fcd77d8d9704f9f0427a4b548404ca4af/host-interaction/uac/bypass/bypass-uac-via-icmluautil.yml#L8

https://attack.mitre.org/techniques/T1548/002 says otherwise: Bypass User Account Control [T1548.002]

Bypass User ~~Access~~ Account Control [T1548.002] 

This is corroborated by the Wikipedia article https://en.wikipedia.org/wiki/User_Account_Control

**Comment by williballenthin** [comment]
closed in 00490c1f68b422acd3488fd7b700a5d1d754fb41 2750b0500da4d8f79b9534794b39fc5e4884bb18 1be8f8070297c066b8580dca963d4e17274b5539 b7692cc662d8905412503a3c6a6dcabb84f490f3

**Comment by williballenthin** [comment]
thank you @evandrix !
