### ISSUE TITLE
murmur_variant

### ISSUE THREAD

**Issue by osardar** [fireeye/capa-rules#46]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your rule idea isn't already filed: [search](https://github.com/fireeye/capa-rules/issues?q=is%3Aissue+is%3Aopen+)

## Summary
I've run in to a variant of murmur hash being used for function resolution. It was easy to detect due to the constants being used. I believe this is a good candidate for a CAPA rule.

## Examples
`KPOT` malware family appears to use murmur hash.

## Features
Constants are the easiest way to identify it.
```
number: 0xcc9e2d51
number: 0x1b873593
number: 0xe6546b64
number: 0x85ebca6b
number: 0xc2b2ae35
```

### Namespace
`data-manipulation`

### References
https://en.wikipedia.org/wiki/MurmurHash

**Comment by re-fox** [comment]
@osardar Do you have a hash of the sample (and offset) that is exhibiting this activity?  I'd be happy to help create a rule.

**Comment by williballenthin** [comment]
i'd have expected https://github.com/fireeye/capa-rules/blob/master/nursery/hash-data-using-murmur3.yml to match this sample. let me triage why its matching as expected.

**Comment by williballenthin** [comment]
@osardar provided me the sample hash offline, and its available on VT:  c66172b12971a329f8d5ff01665f204b

**Comment by williballenthin** [comment]
i think this is already covered and matches correctly:

![image](https://user-images.githubusercontent.com/156560/88317802-0a3c9980-ccd7-11ea-9cb6-3fdee678010b.png)

@osardar can you double check your capa output and see if you have the rule match `hash data using mumur3`?

**Comment by williballenthin** [comment]
in other news, we can graduate this rule, thanks to the example reference!

**Comment by williballenthin** [comment]
Omar was using an internal integration that we have that wasn't up to date on its rules. Rule is working as expected.

Its neat that we're converging on the same set of capabilities!
