### ISSUE TITLE
validate payment card number using luhn algorithm with no lookup table: doesn't match against notepad.exe

### ISSUE THREAD

**Issue by erhlee-bird** [fireeye/capa-rules#534]
## Summary

Rule Name: "validate payment card number using luhn algorithm with no lookup table"

The aforementioned rule doesn't match against a version of notepad.exe (sha256:d66458a3eb1b68715b552b3af32a9d2e889bbf8ac0c23c1afa8d0982023d1ce2).

I don't think the file is actually exhibiting the represented behavior but the rule seems like it should match from how the rule is written.

## Examples

notepad.exe (sha256:d66458a3eb1b68715b552b3af32a9d2e889bbf8ac0c23c1afa8d0982023d1ce2)
Function located at 14000a098

1. There's a loop at 14000ac6d satisfying the loop characteristic requirement

![image](https://user-images.githubusercontent.com/633268/153503581-5b4f6852-d606-4249-a55e-8e311c31011e.png)

2. There is a basic block at 14000a8e2 that satisfies the next inline basic block rule "Digital Root check number*2 < 0x9"

- mnemonic add @ 14000a945
- mnemonic cmp @ 14000a922
- number 9 @ 14000a8ed

![image](https://user-images.githubusercontent.com/633268/153503808-9c8ea1f8-19e6-400d-9cbe-a1abb3055bcc.png)

3. There is a basic block at 14000aa76 that satisfies the next inline basic block rule "Conversion of chr to int (LEA REG,[REG+ -0x30])"

- mnemonic lea @ 14000aa7e
- offset -0x30 @ 14000aa7e

![image](https://user-images.githubusercontent.com/633268/153504284-969ff05b-8dcf-4e00-a6af-49eb4bda6a96.png)

4. There is a basic block at 14000ad3c that satisfies the last inline basic block rule "Final section returning checkum % 10"

- mnemonic div @ 14000ad41
- number 10 @ 14000ad43

![image](https://user-images.githubusercontent.com/633268/153504777-14eb1257-23b5-4983-acb0-b2705b71cb27.png)

## Possible improvements

As a false negative, I think the rule should match according to the specified rule features.

So if this rule did match, I think it would actually be a false positive as a result of the basic block scope being very wide.

If the "Final section returning checkum % 10" rule were at like an instruction scope to look for specifically `div 10` or something along those lines, this probably wouldn't match.

**Comment by mr-tz** [comment]
Thanks for the detailed report! I'll have to take a deeper look at this.

And `instruction` scope or feature (https://github.com/mandiant/capa/issues/767) would help for sure with various FPs.

**Comment by mr-tz** [comment]
We've since added the instruction scope and improved the rule accordingly.

2., 3. and 4. now do not hit anymore, so the function should not and does not match :)
