### ISSUE TITLE
rule: resolve exe path via MSVCRT

### ISSUE THREAD

**Issue by Ana06** [fireeye/capa-rules#82]
@mike-hunhoff
> Example: `69f222da207f6b7fe4bacd3eeb8e7a47e98f5df0a3f8a3b12b96b3c09d5a18b9:401707`
> 
> Windows API:
> * `msvcrt::__p__pgmptr`

**Comment by re-fox** [comment]
Good idea.  

I was looking into creating this rule, but I'm looking for guidance on the best location for the rule.  Somewhere under `host-interaction` I'm guessing.

**Comment by mr-tz** [comment]
Maybe `host-interaction/file-system/` or `host-interaction/file-system/meta`?

**Comment by williballenthin** [comment]
alternatively, `host-interaction/cli` next to `accept command line arguments` since `_pgmptr` is set when run under cmd.exe? just brainstorming.

**Comment by re-fox** [comment]
Thanks for the input @mr-tz @williballenthin.  I'll put the rule under `host-interaction/cli` and if approved, I'll close the issue.

**Comment by re-fox** [comment]
Addressed in https://github.com/fireeye/capa-rules/pull/113
