### ISSUE TITLE
Guidance on rule naming conventions and placement

### ISSUE THREAD

**Issue by re-fox** [fireeye/capa-rules#90]
I have been working through many point of sale malware families and writing signatures for their implementations of Luhn's algorithm.  

The current signature in `/data-encoding/checksum/luhns/` will trigger on most* variants that are utilizing a lookup table, however there are several different implementations of Luhn's that are used in the wild.  Some use different calculations for digit summing, others will preload registers with values that are used in other basic blocks.

I started at first trying to keep appending on to the main rule, but it's quickly becoming a debugging nightmare.  I would like to push up more rules that cover the additional variations, but I don't want someone to have deal with a rule that is a hundred (or so) lines long with or's and and's etc....

I'm looking for the best guidance on how to add these rules up to the repo without giving them overly long descriptive names.  

Right now in my testing repo I have 

```
validate-credit-card-number-with-luhn-algorithm.yml
validate-credit-card-number-with-luhn-algorithm-not-utilizing-lookup-table.yml
validate-credit-card-number-with-luhn-algorithm-neutrino-version.yml
validate-credit-card-number-with-luhn-algorithm-not-utilizing-lookup-table-mod-9.yml
...etc...
```
For my own purposes, that works fine.  For anyone else, I wouldn't expect them to know what any of that means.

Mostly I just want to make sure that I'm contributing in a way that makes sense to everyone who is sitting downstream

**Comment by williballenthin** [comment]
i don't think we've tried to address this before, so i think your guess is as good as mine. lets see if we can work out something that everyone agrees is reasonable.

using the names you've included above makes sense. though, i suspect our users won't know the details of these routines, and will only care about `validate credit card number with luhn algorithm`.

one option would be to have a master rule `validate cc number with luhn` that has a bunch of `match: validate cc number with luhn variant X` statements in it. then, the sub-rules could either be "lib" rules (which don't get displayed), or if we implement https://github.com/fireeye/capa/issues/224, then the subrule would not get displayed anyways.

if we go the "lib" route, then we might run into some annoyances with the linter, which expects lib rules to be in the "lib" directory. maybe we should relax that check.

**Comment by re-fox** [comment]
Storing them in lib makes sense to me, with the master rule being just a collection of matches.

Unfortunately these rules probably don't serve too much of a purpose outside of detecting a single algorithm.  It would be a lot more obvious if the rule was a re-usable building block of logic that could be leveraged in later rules.

I'll tidy up what I have and document the rules as best as possible.  I'm only about halfway through the POS malware families in my repo and have a lot of rule building ahead.  Once I'm ready, I can stage these in a single PR for review and comment.  In the meantime, if a better answer is suggested or thought of,  I'm happy to go that route.

**Comment by mr-tz** [comment]
Closing per @re-fox's comment in #93
